//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public int HouseID { get; set; }
        public string HouseNo { get; set; }
        public string HouseFloor { get; set; }
        public Nullable<int> HouseHostID { get; set; }
    
        public virtual HouseHost HouseHost { get; set; }
    }
}
