//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public int IncomeID { get; set; }
        public string IncomeName { get; set; }
        public string IncomeDescription { get; set; }
        public Nullable<decimal> IncomePrice { get; set; }
        public Nullable<System.DateTime> IncomeDate { get; set; }
    }
}
